hostedZoneName: ""
nullPlatform:
  accountSlug: ""
gcp:
  enabled: false
  serviceAccountKey: ""
azure:
  enabled: false
  subscriptionID: ""
  resourceGroupName: ""
  clientID: ""
  secretKey: "client-secret"
  clientSecret: "" 
  tenantID: ""
  hostedZoneName: ""
cloudflare:
  enabled: false
  secretName: cloudflare-api-token-secret
namespacecontroller:
  name: " "
secretName: "wildcard-tls"