hostedZoneName: ""
nullPlatform:
  accountSlug: ""
gcp:
  enabled: false
  serviceAccountKey: ""
azure:
  enabled: false
  subscriptionID: ""
  resourceGroupName: ""
  clientID: ""
  secretKey: "client-secret"
  clientSecret: "" 
  tenantID: ""
  hostedZoneName: ""
  secretName: "azuredns-config"
cloudflare:
  enabled: false
  secretName: "cloudflare-api-token-secret"
  apiToken: ""
namespaceController:
  name: ""
secretName: "wildcard-tls"