hostedZoneName: ""
nullPlatform:
  accountSlug: ""
gcp:
  enabled: false
  serviceAccountKey: ""
azure:
  enabled: false
  subscriptionID: ""
  resourceGroupName: ""
  clientID: ""
  secretKey: "client-secret"
  clientSecret: "" 
  tenantID: ""
  hostedZoneName: ""
  secretName: "azuredns-config"
cloudflare:
  enabled: false
<<<<<<< HEAD
  secretName: "cloudflare-api-token-secret"
  apiToken: ""
namespaceController:
  name: ""
=======
  secretName: cloudflare-api-token-secret
namespacecontroller:
  name: " "
>>>>>>> f72974e (feat(certmanager-config))
secretName: "wildcard-tls"
private:
  enabled: false
  domainName: ""
certificate:
  name: "wildcard-tls-internal"
  namespace: ""
  secretName: "wildcard-tls-internal"
  issuerRef:
    name: "letsencrypt-internal"
    kind: "ClusterIssuer"