hostedZoneName: ""
nullPlatform:
  accountSlug: ""
cloudProvider: ""
route53:
  region: ""
gcp:
  projectId: ""
azure:
  subscriptionID: ""
  resourceGroupName: ""
  clientID: ""
  tenantID: ""
  hostedZoneName: ""
cloudflare:
  secretName: "cloudflare-api-token-secret"
  apiToken: ""
oci:
  region: ""
  compartmentOCID: ""
namespaceController:
  name: "gateways"
secretName: "wildcard-tls"
private:
  enabled: true
  domainName: ""
certificate:
  name: "wildcard-tls-internal"
  namespace: "gateways"
  secretName: "wildcard-tls-internal"
  issuerRef:
    name: "letsencrypt-internal"
    kind: "ClusterIssuer"
