hostedZoneName: ""
nullPlatform:
  accountSlug: ""
route53:
  enabled: false
  region: ""
  role: ""
  auth:
    kubernetes:
      serviceAccountRef:
        name: ""
gcp:
  enabled: false
  serviceAccountKey: ""
azure:
  enabled: false
  subscriptionID: ""
  resourceGroupName: ""
  clientID: ""
  secretKey: "client-secret"
  clientSecret: "" 
  tenantID: ""
  hostedZoneName: ""
  secretName: "azuredns-config"
cloudflare:
  enabled: false
  secretName: "cloudflare-api-token-secret"
  apiToken: ""
namespaceController:
  name: ""
secretName: "wildcard-tls"
private:
  enabled: false
  domainName: ""
certificate:
  name: "wildcard-tls-internal"
  namespace: ""
  secretName: "wildcard-tls-internal"
  issuerRef:
    name: "letsencrypt-internal"
    kind: "ClusterIssuer"