{{- if .Values.githubTokenInit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.githubTokenInit.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  APP_ID: "{{ .Values.githubTokenInit.secretKeys.appId | b64enc }}"
  INSTALLATION_ID: "{{ .Values.githubTokenInit.secretKeys.installationId | b64enc }}"
  PRIVATE_KEY: "{{ .Values.githubTokenInit.secretKeys.privateKey }}"
{{- end }}