{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: nullplatform-critical-{{ .Release.Name }}
value: {{ .Values.priorityClass.value }}
globalDefault: false
description: "Highest priority for critical system pods"
{{- end }}
