{{- if and .Values.serviceAccount.create .Values.serviceAccount.role.create (eq .Values.serviceAccount.role.scope "namespace") (not .Values.serviceAccount.role.import) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent.serviceAccountName" . }}-role
  namespace: {{ .Values.namespace }}
rules:
  {{- toYaml .Values.serviceAccount.role.rules | nindent 3 }}
{{- end }}