{{- if and .Values.serviceAccount.create (not .Values.serviceAccount.clusterWide) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name:  {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "agent.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
