{{- if and .Values.serviceAccount.create .Values.serviceAccount.role.create (eq .Values.serviceAccount.role.scope "namespace") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-binding
  namespace: {{ .Values.namespace }}
subjects: 
  - kind: ServiceAccount
    name:  {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  {{- if .Values.serviceAccount.role.import }}
  name: {{ .Values.serviceAccount.role.name }}
  {{- else }}
  name: {{ include "agent.serviceAccountName" . }}-role
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}