{{- if and .Values.azure.enabled .Values.azure.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azure.secretName }}}}
  namespace:  {{ .Values.namespaceController.name }}
type: Opaque
stringData:
  {{ .Values.azure.secretKey | default "client-secret" }}: {{ .Values.azure.clientSecret | quote }}
{{- end }}