apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.secretName }}
  namespace:  {{ .Values.namespaceController.name }}
spec:
  secretName: {{ .Values.secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.{{ .Values.hostedZoneName }}"
  dnsNames:
  - "{{ .Values.hostedZoneName }}"
  - "*.{{ .Values.hostedZoneName }}"
  {{- if .Values.nullPlatform.accountSlug }}
  - "*.{{ .Values.nullPlatform.accountSlug }}.{{ .Values.hostedZoneName }}"
  {{- end }}
