{{- if .Values.private.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name | default "wildcard-tls-internal" }}
  namespace: {{ .Values.namespacecontroller.name | default "openshift-ingress" }}
spec:
  secretName: {{ .Values.certificate.secretName | default "wildcard-tls-internal" }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name | default "letsencrypt-internal" }}
    kind: {{ .Values.certificate.issuerRef.kind | default "ClusterIssuer" }}
  commonName: "*.{{ .Values.private.domainName }}"
  dnsNames:
    - {{ .Values.private.domainName }}
    - "*.{{ .Values.private.domainName }}"
{{- end }}