{{- if eq .Values.cloudProvider "cloudflare" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.secretName }}
  namespace: {{ .Values.namespaceController.name }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}