{{- if .Values.private.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-internal
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it@nullplatform.io
    privateKeySecretRef:
      name: letsencrypt-internal
    solvers:
      - dns01:
          {{- if .Values.route53.enabled }}
          route53:
            region: {{ .Values.route53.region }}
            role: {{ .Values.route53.role }}
            auth:
              kubernetes:
                serviceAccountRef:
                  name: {{ .Values.route53.auth }}
          {{- end }}
          {{- if .Values.azure.enabled }}
          azureDNS:
            clientID: {{ .Values.azure.clientID }}
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: {{ .Values.azure.subscriptionID }}
            tenantID: {{ .Values.azure.tenantID }}
            resourceGroupName: {{ .Values.azure.resourceGroupName }}
            hostedZoneName: {{ .Values.azure.hostedZoneName }}
            environment: AzurePublicCloud
          {{- else }}
          {}
          {{- end }}
{{- end }}