{{- if .Values.private.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-internal
  # ClusterIssuer es un recurso global, no lleva namespace, pero no rompe nada si lo dejas.
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it@nullplatform.io
    privateKeySecretRef:
      name: letsencrypt-internal
    solvers:
      - selector:
          dnsZones:
            - "{{ .Values.private.domainName }}"
        dns01:
         {{- if eq .Values.cloudProvider "gcp" }}
          cloudDNS:
            project: "{{ .Values.gcp.projectId }}"
          {{- else if eq .Values.cloudProvider "azure" }}
          azureDNS:
            clientID: {{ .Values.azure.clientID }}
            subscriptionID: {{ .Values.azure.subscriptionID }}
            tenantID: {{ .Values.azure.tenantID }}
            resourceGroupName: {{ .Values.azure.resourceGroupName }}
            hostedZoneName: {{ .Values.azure.hostedZoneName }}
            environment: AzurePublicCloud
            config:
              useWorkloadIdentityExtension: true
            {{- else if eq .Values.cloudProvider "cloudflare" }}
            cloudflare:
              apiTokenSecretRef:
                name: {{ .Values.cloudflare.secretName | default "cloudflare-api-token-secret" }}
                key: api-token
            {{- else if eq .Values.cloudProvider "aws"}}
            route53:
              region: {{ .Values.route53.region}}
          {{- end }}
{{- end }}
