apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace:  {{ .Values.namespaceController.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it@nullplatform.io
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        {{- if .Values.route53.enabled }}
        route53:
          region: {{ .Values.route53.region }}
          role: {{ .Values.route53.role }}
          auth:
            kubernetes:
              serviceAccountRef:
                name: {{ .Values.route53.auth }}
        {{- end }}
        {{- if .Values.gcp.enabled }}
        cloudDNS:
          project: "{{ .Values.gcp.projectId }}"
          # The secret containing the service account key JSON with DNS permissions
          serviceAccountSecretRef:
            name: gcp-cloud-dns-service-account
            key: key.json
        {{- end }}
          {{- if .Values.azure.enabled }}
        azureDNS:
          subscriptionID: {{ required "azure.subscriptionID is required" .Values.azure.subscriptionID | quote }}
          tenantID:       {{ required "azure.tenantID is required" .Values.azure.tenantID | quote }}
          resourceGroupName: {{ required "azure.resourceGroupName is required" .Values.azure.resourceGroupName | quote }}
          hostedZoneName:    {{ .Values.hostedZoneName  }}
          environment: AzurePublicCloud
          clientID: {{ required "azure.clientID is required" .Values.azure.clientID | quote }}
          clientSecretSecretRef:
            name: {{ .Values.azure.secretName }}
            key:  {{ .Values.azure.secretKey | default "client-secret" | quote }}
          {{- end }}

          {{- if .Values.cloudflare.enabled }}
        cloudflare:
          apiTokenSecretRef:
            name: {{ .Values.cloudflare.secretName | default "cloudflare-api-token-secret" }}
            key: api-token
          {{- end }}
     