{{- if eq .Values.global.provider "aro" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluent-bit-metrics
  namespace: openshift-monitoring
  labels:
    app: nullplatform-log-controller
spec:
  namespaceSelector:
    matchNames:
      - nullplatform-tools
  selector:
    matchLabels:
      Name: nullplatform-log-controller
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: prometheus
      scheme: http
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_host_ip]
          targetLabel: host_ip
{{- end }}