{{- if .Values.global.installGatewayV2Crd }}
apiVersion: batch/v1
kind: Job
metadata:
  name: install-gateway-api-crds
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  template:
    spec:
      serviceAccountName: nullplatform-crd-installer-sa
      containers:
      - name: install-crds
        image: docker.io/bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
            { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=444631bfe06f3bcca5d0eadf1857eac1d369421d" | kubectl apply -f -; }
      restartPolicy: OnFailure
{{- end }}
