apiVersion: v2
name: nullplatform-agent
description: Agent used to interact with services, scopes and telemetry inside a cluster
type: application
version: 2.34.0
appVersion: 2.32.1
keywords:
  - nullplatform
  - agent
  - kubernetes
home: https://nullplatform.com
sources:
  - https://github.com/nullplatform/helm-charts
maintainers:
  - name: Nullplatform
    email: support@nullplatform.com
